
/*!
 * {{ type }} Package container for {{ package }}
 *
 * ----------------------------------------------------------------------------
 *
 * This script has been generated by OS.js package creation utility
 * and you should add some sort of description here.
 *
 * Check for TODO markings to fill in missing events and initialization
 * code.
 *
 * ----------------------------------------------------------------------------
 *
 * Copyright (c) 2011-2012, Anders Evenrud <andersevenrud@gmail.com>
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @package     OSjs.Packages
 * @author      Anders Evenrud <andersevenrud@gmail.com>
 * @licence     Simplified BSD License
 */
OSjs.Packages.{{ package|e }} = (function($, undefined) {

  /**
   * @desc Translation Table
   */
  var _LINGUAS = {{ linguas }};
{%- if type == "PanelItem" %}

  /**
   * {{ package }} -- {{ type }} Package Namespace
   *
   * @param PanelItem     PanelItem           PanelItem API Reference
   * @param Panel         panel               Panel Instance Reference
   * @param API           API                 Public API Reference
   * @param Dict          argv                Launch arguments
   */
  return function(PanelItem, panel, API, argv) {

    var LABELS = _LINGUAS[API.system.language()] || _LINGUAS["{{ default_language|e }}"];

    ///////////////////////////////////////////////////////////////////////////
    // MAIN CLASS
    ///////////////////////////////////////////////////////////////////////////

    /**
     * {{ package }} -- Main PanelItem Class
     * @class
     */
    var {{ package|e }} = PanelItem.extend({

      /**
       * {{ package }}::init() -- Constructor
       */
      init : function() {
        this._super("{{ package|e }}");
      },

      /**
       * {{ package }}::destroy() -- Destruction method
       */
      destroy : function() {
        this._super();
      },

      /**
       * {{ package }}::run() -- Called when created/started
       * @return  bool
       */
      create : function(pos) {
        var _ret = this._super(pos);

        // TODO: Do your stuff here

        return _ret;
      }
    });

    return new {{ package|e }}();
  };

{%- else if type == "Application" %}

  /**
   * {{ package }} -- {{ type }} Package Namespace
   *
   * @param GtkWindow     GtkWindow            GtkWindow API Reference
   * @param Application   Application          Application API Reference
   * @param API           API                  Public API Reference
   * @param Dict          argv                 Launch arguments
   * @param Array         _windows             An array of window arguments to restore
   */
  return function(GtkWindow, Application, API, argv, _windows) {

    /**
     * @desc Localized Translations
     */
    var LABELS = _LINGUAS[API.system.language()] || _LINGUAS["{{ default_language|e }}"];

    /**
     * @desc Accepted MIME type(s)
     */
    var MIMES  = {{ mimes }};

    ///////////////////////////////////////////////////////////////////////////
    // WINDOWS
    ///////////////////////////////////////////////////////////////////////////
{%- for w in windows %}

    /**
     * Window_{{ w.name }} -- GtkWindow Class for {{ w.name }}
     * @class
     */
    var Window_{{ w.name|escape }} = GtkWindow.extend({

      /**
       * Window_{{ w.name }}::init() -- Constructor
       * @param   Application     app     Application reference
       */
      init : function(app) {
        this._super("Window_{{ w.name|e }}", {{ w.is_dialog }}, app, _windows);
        this._content = $("{{ w.html|addslashes }}").html();

{{ w.code_init }}
        // TODO: Add your initial vars/attrs here
      },

      /**
       * Window_{{ w.name }}::destroy() -- Destruction method
       */
      destroy : function() {
        this._super();
      },
{% for s in w.signals %}
      /**
       * Window_{{ w.name }}::{{ s.handler }}()
       * @signal  {{ s.id }} > {{ s.signal }}
       * @return  void
       */
      {{ s.handler }} : function(el, ev) {
  {%- if s.template == "DefaultFileOpen" %}
        // TODO: Create callback here
        var my_callback = function(fname) {};

        var my_filename = this.app._getArgv('path');
        this.app.defaultFileOpen(function(fname) {
          my_callback(fname);
        }, MIMES, null, my_filename);
  {%- else if s.template == "DefaultFileSave" %}
        // TODO: Fill contents, and create callback here
        var my_content  = "";
        var my_callback = function(fname) {};

        var my_filename = this.app._getArgv('path');
        if ( my_filename ) {
          this.app.defaultFileSave(my_filename, my_content, function(fname) {
            my_callback(fname);
          }, MIMES, undefined, false);
        }
  {%- else if s.template == "DefaultFileSaveAs" %}
        // TODO: Fill contents, and create callback here
        var my_content  = "";
        var my_callback = function(fname, fmime) {};

        var my_filename = this.app._getArgv('path');
        this.app.defaultFileSave(my_filename, my_content, function(fname) {
          my_callback(fname);
        }, MIMES, undefined, true);
  {%- else if s.template == "DefaultClose" %}
        this.close();
  {%- else if s.template == "DefaultClipboardCopy" %}
        this.app._clipboard("copy");
  {%- else if s.template == "DefaultClipboardPaste" %}
        this.app._clipboard("paste");
  {%- else if s.template == "DefaultClipboardCut" %}
        this.app._clipboard("cut");
  {%- else if s.template == "DefaultClipboardDelete" %}
        this.app._clipboard("delete");
  {%- else if s.template == "DefaultClipboardSelectAll" %}
        this.app._clipboard("select");
  {%- else %}
    {%- if s.signal == "file-set" %}
        var self = this;

        var my_path     = this.$element.find(".{{ s.id }} input[type=text]").val();
        this.app.createFileDialog(function(fname) {
          self.$element.find(".{{ s.id|e }} input[type=text]").val(fname);
          self.$element.find(".{{ s.id|e }} input}type=hidden]").val(fname);
        }, MIMES, "open", dirname(my_path));
    {%- else if s.signal == "input-activate" %}
        // TODO: No code generated (not needed)
    {%- else %}
        // TODO: Implement your event here
    {%- endif %}
  {%- endif %}
      },
{% endfor %}
      /**
       * Window_{{ w.name }}::create() -- Called when created/started
       * @param   String    id            Window ID
       * @param   Function  mcallback     Callback when finished creating window
       * @return  bool
       */
      create : function(id, mcallback) {
        var el = this._super(id, mcallback);
        var self = this;

        if ( el ) {
{% for s in w.signals %}
          // Signal: [{{ s.id }}]::{{ s.signal }}()
  {%- if s.signal == "file-set" %}
          el.find(".{{ s.id }} button").click(function(ev) {
            self.{{ s.handler }}(this, ev);
          });
  {%- else if s.signal == "input-activate" %}
          el.find(".{{ s.id }}").keypress(function(ev) {
            var k = ev.keyCode || ev.which;
            if ( k == 13 ) {
              self.{{ s.handler }}(this, ev);
            }
          });
  {%- else %}
          el.find(".{{ s.id }}").{{ s.signal }}(function(ev) {
            self.{{ s.handler }}(this, ev);
          });
  {%- endif %}
{% endfor %}

          // TODO: Do your stuff here

          return true;
        }

        return false;
      }
    });

{%- endfor %}

    ///////////////////////////////////////////////////////////////////////////
    // APPLICATION
    ///////////////////////////////////////////////////////////////////////////

    /**
     * {{ package }} -- Main Application Class
     * @class
     */
    var {{ package|e }} = Application.extend({

      /**
       * {{ package }}::init() -- Constructor
       */
      init : function() {
        this._super("{{ package|e }}", argv);
        this._compability = {{ compability }};
      },

      /**
       * {{ package }}::destroy() -- Destruction method
       */
      destroy : function() {
        this._super();
      },

      /**
       * {{ package }}::run() -- Called when started
       * @return  void
       */
      run : function() {
        {{ code_prepend }}

        this._super({{ glade_window }});

        {{ code_append }}

        // TODO: Do your stuff here
      }
    });

    return new {{ package|e }}();
  };

{% else -%}

  /**
   * {{ package }} -- {{ type }} Package Namespace
   *
   * @param Service       Service             Service API Reference
   * @param API           API                 Public API Reference
   * @param Dict          argv                Launch arguments
   */
  return function(Service, API, argv) {

    var LABELS = _LINGUAS[API.system.language()] || _LINGUAS["{{ default_language|e }}"];

    ///////////////////////////////////////////////////////////////////////////
    // MAIN CLASS
    ///////////////////////////////////////////////////////////////////////////

    /**
     * {{ package }} -- Main Application/Service Class
     * @class
     */
    var {{ package|e }} = Service.extend({

      /**
       * {{ package }}::init() -- Constructor
       */
      init : function() {
        this._super("{{ package|e }}", "{{ icon|e }}");
      },

      /**
       * {{ package }}::destroy() -- Destruction method
       */
      destroy : function() {
        this._super();
      },

      /**
       * {{ package }}::run() -- Called when started
       * @return  void
       */
      run : function() {
        this._super();
      }
    });

    return new {{ package|e }}();
  };

{%- endif %}
})($);

