#!/bin/sh
#
# Example X initialization script
#
xsetroot -cursor /usr/share/icons/whiteglass
xsetroot -cursor_name left_ptr
/usr/bin/start-pulseaudio-x11
nohup node ~/OS.js/client.js 3000 `whoami` >/dev/null 2>&1 &
sleep 3
exec ~/OS.js/vendor/launcher/session-launch
